server:
  port: 8087

spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/ead-authuser
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.MySqlDialect
      jdbc:
        lob.non-contextual-creation:  true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always




